# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - qcomr

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://qcomr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1eaec97dbea04d5786e7a5cc0738ac54 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7025919e095d4f0d808c09c8d49cca18 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: qcomr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1eaec97dbea04d5786e7a5cc0738ac54 }}/hello-express:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'qcomr'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9b5fdf53d88644c5b18be9148d0ab054 }}
        images: 'qcomr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1eaec97dbea04d5786e7a5cc0738ac54 }}/hello-express:${{ github.sha }}'